# tmux config

unbind C-b
set -g prefix C-a
set -g renumber-windows on
set -g status-fg white
setw -g mode-keys vi
set -g default-terminal "screen-256color"
set -g focus-events on
bind l select-pane -R
